---
- name: keep my dev snow instance alive
  hosts: localhost
  gather_facts: false
  vars:
#    snow_username: admin
#    snow_password: mysnowpword
#    snow_instance: dev99999
    snow_caller_id: System Administrator

  tasks:
    - name: Create an incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        data:
          short_description: "Keep Alive Ticket"
#          description: Something here useful
          caller_id: "{{ snow_caller_id }}"
          severity: 3
          priority: 5
      register: new_incident

    - set_fact:
        ticket_number: "{{ new_incident.record.number }}"

    - name: Delete the keepalive incident
      snow_record:
        username: "{{ snow_username }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: absent
        number: "{{ ticket_number }}"
#      failed_when: false
