---
- name: Calling the role to perform windows web or TCP based tshooting
  hosts: dc
  gather_facts: false
  vars:
    # adjust this port when using tcp port tshooting, otherwise leave 0
#    tcp_port: '0'

    # change this to whatever the test target is(web or tcp based)
#    test_url: gregsowell.com

    # change this to the client you are having issues from
#    test_client: client1

    # this is the outside of your network test client
    test_canary: client2

    # this overrides the default settings above with those from SNOW
    tcp_port: "{{ variable_3 }}"
    test_url: "{{ variable_2 }}"
    test_client: "{{ variable_1 }}"

#    snow_username: username
#    snow_password: password
#    snow_instance: myinstance


  tasks:
#  - name: debug port to see its format
#    debug:
#      var: tcp_port

  - name: Include role for tshooting
    include_role:
      name: snow-tshoot
